### ISSUE TITLE
1.8.1 Release

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#1683]
**Task list:**
- [x] Go through [all PRs](https://github.com/PointCloudLibrary/pcl/pulls?q=is%3Aopen+is%3Apr+milestone%3Apcl-1.8.1) for the milestone
- [x] Update Changelog #1682 
- [x] Start a release branch
- [x] Revert #1587  
- [x] Bump version to 1.8.1 in CMakeLists.txt
- [x] Try to build and test on all relevant platforms
- [x] Finalize changelog and fix the release date
- [x] Tag
- [x] Remove the release branch
- [x] Add Windows installers to GitHub release page
- [x] Add OSX installers to GitHub release page
- [x] Add link doc link to tutorials page
- [x] Bump version to 1.8.1-dev in CMakeLists.txt
- [x] Send announcements to the mailing lists
- [x] Throw a party!

Future people: Don't forget to revise all new tutorials to modify the minimum required version from 1.x.x.99 to whatever the new version is.

**Comment by taketwo** [comment]
Also update PCL version in [CMakeLists.txt](https://github.com/PointCloudLibrary/pcl/blob/master/CMakeLists.txt#L194).

**Comment by UnaNancyOwen** [comment]
I would like to add support Visual C++ 2017 in PCL 1.8.1.
Could you consider to merge these Pull Request (#1823, #1830) for it?

**Comment by taketwo** [comment]
Sorry for the unnecessary delay, merged now.

**Comment by UnaNancyOwen** [comment]
Is official web in updatable?
It seems that it has not been updated for a long long time.
I think we should update it to the latest information.

BTW : 
I'm ready to generate all-in-one installer of next version.
I would like to distribute the next version installer from official web.
Who manages accounts of sourceforge.net?

**Comment by UnaNancyOwen** [comment]
We should be confirm that able to build PCL 1.8.1 on Visual Studio before release PCL 1.8.1. Because, It has not been tested with CI.

- [ ] Build Test on Windows

**Comment by SergioRAgostinho** [comment]
It was thinking it would be nice this time to include some binaries on the github release page for the three platforms. I know we are using cpack for the packaging. I was just wondering which compile options do you normally pass when you want to compile pcl for deployment on an external environment?

**Comment by taketwo** [comment]
I think this is something @jspricke will know.

So, once #1917 is merged, we can start with the release procedure? I updated the list in the root post.

**Comment by UnaNancyOwen** [comment]
Could you discuss this proposal (#1918) before release procedure?
I would like to merge this proposal to support PCL in [Vcpkg](https://github.com/Microsoft/vcpkg/pull/1283). (Currently, It is under implementation.)

**Comment by SergioRAgostinho** [comment]
> We should be confirm that able to build PCL 1.8.1 on Visual Studio before release PCL 1.8.1. Because, It has not been tested with CI.  Build Test on Windows

IIRC the tests should be failing with some precision issues on Windows, similar to the ones in OSX. It's something on the backlog but not something we'll address on this release.

**Comment by jspricke** [comment]
Regarding adding binaries, adding Windows binaries makes sense, @UnaNancyOwen could you help with that? That would be awesome! For the other platforms (I assume you mean MacOS and Ubuntu/Debian) it doesn't make sense as it's the job of the distribution maintainer. So once we release a new version, they have to integrate into their system. Also we don't use cpack for that.

**Comment by SergioRAgostinho** [comment]
I understand that comment regarding ubuntu/debian. Regarding MacOS, there's not exactly an official distribution maintainer? Are you referring to Homebrew?

**Comment by jspricke** [comment]
I don't use Apple, but Homebrew should be ok.

**Comment by UnaNancyOwen** [comment]
@jspricke I can provide the PCL 1.8.1 All-in-one Installer.
I have a plan to create four installer of MSVC 2017 x64/x86, MSVC2015 x64/x86.
I would like to distribute it on stable server like a github releae page or [sourceforge.net](https://sourceforge.net/projects/pointclouds/). (My current distribution server is unstable...)

**Comment by SergioRAgostinho** [comment]
My idea was to try to add them to the GitHub release page. They support placing binaries, although I'm not sure if there's a maximum file size it supports.

**Comment by taketwo** [comment]
The release branch is [online](https://github.com/PointCloudLibrary/pcl/tree/pcl-1.8.1rc) with the ABI breaking PR reverted and version bumped to 1.8.1. Anyone cares to tag 1.8.1rc1 on it and send an announcement?

**Comment by jspricke** [comment]
Awesome work, thank you all!
@taketwo can you send a mail to the pcl-dev@ list?

**Comment by taketwo** [comment]
Ok, I've tagged 1.8.1rc1 and sent an announcement to both pcl-dev and pcl-users.

**Comment by SergioRAgostinho** [comment]
@taketwo Thanks for all the help in this final stretch  👊

**Comment by SergioRAgostinho** [comment]
So I've just built everything for Mac. It built, but no news there. I didn't run the tests because I know they're failing ^^

I've decided to create a binary package and experimentally release the binaries on the release page. I'll ask people to give it a try.

**Comment by UnaNancyOwen** [comment]
I'm building PCL 1.8.1 RC1 to create an All-in-one Installer. Please wait a few days.

**Comment by SergioRAgostinho** [comment]
> I'm building PCL 1.8.1 RC1 to create an All-in-one Installer. Please wait a few days.

Can you also package an archive with simply headers, libs, binaries and shareables, aka contents of the install folder only.

**Comment by UnaNancyOwen** [comment]
@SergioRAgostinho Is that mean that to packaging in zip archive instead of create installer?
I think that our support costs will increase, because many newcomer developers are unfamiliar to install using zip archive.
Do you have any reasons?

**Comment by SergioRAgostinho** [comment]
Not instead. Additional to the All-In-One. I want to include both.

**Comment by UnaNancyOwen** [comment]
@SergioRAgostinho OK, I understood your plan. I will create both an installer and a zip archive.

**Comment by UnaNancyOwen** [comment]
@SergioRAgostinho I created PCL 1.8.1 binaries (installer and archive) for Visual Studio 2017.
How can I upload it to GitHub?

**Comment by SergioRAgostinho** [comment]
The difference in size between the windows and mac archives is crazy 😮  What did you include on the windows zip @UnaNancyOwen ?

I disabled every optional dependency except VTK, and built with the default modules included, no simulation, app and examples. I also built with -O3 and without SSE flags.

**Comment by UnaNancyOwen** [comment]
@SergioRAgostinho It includes files excluding debug configuration exe files and 3rdParty libraries files from PCL built with the following configuration. It static linked all dependent files except OpenNI2, because It is the default settings of PCL on Windows.
https://gist.github.com/UnaNancyOwen/59319050d53c137ca8f3#file-pcl1-8-1-md

Shall I change the build configuration to reduce the size of zip archive?

**Comment by UnaNancyOwen** [comment]
Sorry, I forgot to exclude local documents. It is unnecessary. (196MB->108MB)

From there, if exclude the release configuration exe files, archive size will be 59.2MB.
It means that archive contains only library files (*.dll, *.lib and headers).

It is necessary change build configuration to further reduce size.

@SergioRAgostinho What do you think?

**Comment by SergioRAgostinho** [comment]
>  Sorry, I forgot to exclude local documents. It is unnecessary. 

Yeah, I would not bundle the docs with the binaries.

> From there, if exclude the release configuration exe files (such as pcl_viewer_release.exe), archive size will be 59.2MB. It means that archive contains only library files (*.dll, *.lib and headers).

I kept all executables which are being built, basically tools.

In true honesty, there's no limit whatsoever imposed by GitHub on the size of the binary package. I just noticed the sizes between ours was very different and was curious about the reason.

I also noticed that in your archive you've included both Debug and Release configurations from MSVC. I would say for this is better to make two separate archives. Although, I only uploaded my Release build. 😅

**Comment by UnaNancyOwen** [comment]
@SergioRAgostinho OK, I replaced the archives that excluded local documents.

**Comment by xufangda** [comment]
Can anyone provide a PDB package for PCL1.8.1?

**Comment by jspricke** [comment]
what is a PDB package? Can you provide a link?

**Comment by SergioRAgostinho** [comment]
Aren't those debug symbols from MSVC?

**Comment by UnaNancyOwen** [comment]
@xufangda Thank you for trying to debug on Windows!
I uploaded pdb archives to the release page.
Give it a try and please report any problems.

**Comment by SergioRAgostinho** [comment]
@UnaNancyOwen have a look at this http://www.pcl-users.org/LNK2038-error-when-trying-to-compile-PCL-debug-and-release-mixup-pcl-1-8-0-td4044738.html#a4044755

You're bundling Qt and VTK right? Is QT-VTK not installed by default?

**Comment by UnaNancyOwen** [comment]
@SergioRAgostinho The pre-built PCL (and VTK) that included in the all-in-one installer has been disabled Qt option. If users want to use it, They need build PCL (and QVTK) from source code.

**Comment by SergioRAgostinho** [comment]
Is there a technical limitation or something? Aren't you bundling both dependencies in that installer?

**Comment by UnaNancyOwen** [comment]
@SergioRAgostinho The prebuilt Qt that distributing on the Qt official web doesn't include binaries for some target. (e.g. Qt 5.9.1 package include binaries for msvc2015 x86, x64, and msvc2017 x64. But, It doesn't include msvc2017 x86. I don't know this reason.)
We need to distribute the pre-built PCL with same options for some targets, but Qt makes it difficult.

Also, Qt had not been default supported in PCL 1.6.0 All-in-one Installer.
At that time, Qt (and QVTK) was distributed separately from the all-in-one installer, and users had need build PCL with these libraries from source code yourself.

I think the all-in-one installer does not support to include Qt.
And, That users should be build yourself, if users want to use PCL with Qt.

**Comment by SergioRAgostinho** [comment]
> But, It doesn't include msvc2017 x86. I don't know this reason.
We need to distribute the pre-built PCL with same options for some targets, but Qt makes it difficult.

Providing Qt binaries compiled by yourself is not an option?

**Comment by UnaNancyOwen** [comment]
@SergioRAgostinho I think it is difficult...
I propose to use Vcpkg instead of All-in-one Installer.
I think that PCL port (under development) of Vcpkg can support the Qt option.
If users want to use PCL with Qt, They can easily install it by executing a simple command with Vcpkg.

```
vcpkg install pcl:x86-windows
```

**Comment by taketwo** [comment]
It's been about two weeks now. Should we cherry-pick some commits from master, tag "rc2" and release in a week or so?

**Comment by taketwo** [comment]
OK, we have merged 7 PRs since the first RC, here is my proposal:
  * <strike> #1920 </strike> already cherry-picked
  * #1923 cherry-pick
  * #1926 cherry-pick
  * #1929 cherry-pick
  * <strike> #1925 </strike> minor
  * <strike> #1724 </strike> we may want to revise
  * <strike> #1933 </strike> tutorial text

**Comment by SergioRAgostinho** [comment]
Agree with everything. If it's not too cumbersome I would do the last one, regarding the tutorial update, but it's really optional.

**Comment by taketwo** [comment]
I've cherry-picked the commits (including tutorial update) and tagged a [new RC](https://github.com/PointCloudLibrary/pcl/releases/tag/pcl-1.8.1rc2). Will send a message to the lists.

**Comment by SergioRAgostinho** [comment]
I just recalled that the changelog is not updated with these last cherry picks. We should do it before the final release.

**Comment by taketwo** [comment]
Yes. Also the release date.

**Comment by UnaNancyOwen** [comment]
I just uploaded rc2 binaries.

**Comment by taketwo** [comment]
There was a question regarding msvc2015 binaries on the mail list. Is it planned?

**Comment by UnaNancyOwen** [comment]
@taketwo Yes, I have a plan to create PCL All-in-one Installer for msvc2015 when PCL 1.8.1 will be released.

**Comment by taketwo** [comment]
What about releasing finally? Or are we blocked for an indefinite period by #1949?

**Comment by jspricke** [comment]
Fine with me. We can still do a new release once it's fixed.

Thanks for pushing this!

**Comment by UnaNancyOwen** [comment]
It is waiting for a reply.
Please wait a little.

**Comment by taketwo** [comment]
OK, I'll release later today.

**Comment by UnaNancyOwen** [comment]
@taketwo I changed the milestone of this issue (https://github.com/PointCloudLibrary/pcl/issues/1949) to pcl-1.9.0 from pcl-1.8.1.

**Comment by UnaNancyOwen** [comment]
I just uploaded PCL 1.8.1 binaries for Windows.
