### ISSUE TITLE
1.9.1 Release

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#2629]
# Task list
- [x] Go through all PRs for the [milestone](https://github.com/PointCloudLibrary/pcl/milestone/7)
- [x] Update Changelog
- [x] Start a release branch
- [x] (If needed) Revert whatever unintentional API/ABI breakage that might have occurred in the release branch
- [x] Bump version to x.x.x in CMakeLists.txt
- [x] Bump version off the release badge in README.md
- [x] Find replace all occurrences of x.x.x.99 CMake requirements in the tutorials and examples
- [x] Try to build and test on all relevant platforms
- [x] Finalize changelog and fix the release date
- [x] Tag
- [x] Remove the release branch
- [x] Add binaries to the GitHub release page.
- [x] Add link doc link to tutorials page
- [x] Bump version to x.x.x-dev in CMakeLists.txt
- [ ] Send announcements to the mailing lists regarding 1.9.0 and 1.9.1
- [ ] Throw **two** parties: 1.9.0 and 1.9.1

**Comment by taketwo** [comment]
I propose to include #2612 in this release.

**Comment by SergioRAgostinho** [comment]
I've created the milestone and added it.

**Comment by SergioRAgostinho** [comment]
@claudiofantacci you are able to build with GPU on mac right? You haven't seen these before?
```
[  1%] Building CXX object gpu/containers/CMakeFiles/pcl_gpu_containers.dir/src/device_memory.cpp.o
nvcc fatal   : Unsupported gpu architecture 'compute_72'
nvcc fatal   : Unsupported gpu architecture 'compute_72'
CMake Error at pcl_cuda_features_generated_normal_3d.cu.o.RelWithDebInfo.cmake:219 (message):
  Error generating
  /Users/neglective/Development/3rdparty/pcl/build/cuda/features/CMakeFiles/pcl_cuda_features.dir/src/./pcl_cuda_features_generated_normal_3d.cu.o


CMake Error at pcl_cuda_segmentation_generated_connected_components.cu.o.RelWithDebInfo.cmake:219 (message):
  Error generating
  /Users/neglective/Development/3rdparty/pcl/build/cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/src/./pcl_cuda_segmentation_generated_connected_components.cu.o


make[2]: *** [cuda/features/CMakeFiles/pcl_cuda_features.dir/src/pcl_cuda_features_generated_normal_3d.cu.o] Error 1
make[2]: *** [cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/src/pcl_cuda_segmentation_generated_connected_components.cu.o] Error 1
make[1]: *** [cuda/features/CMakeFiles/pcl_cuda_features.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/all] Error 2
```

**Comment by claudiofantacci** [comment]
@SergioRAgostinho yes, I have that too. My guess is that we have `CUDA_ARCH_BIN` set to `3.0 3.5 5.0 5.2 5.3 6.0 6.1 7.0 7.2` that is provided by CMake, while our nvcc version 9 does not support compilation units with CUDA architectures `7.0+`.
I did not notice this before because I always manually set `CUDA_ARCH_BIN` to my local architecture that is `3.0`. Notice also that CUDA architecture `2.*` has also been dropped because NVIDIA no longer supports it.

**Comment by claudiofantacci** [comment]
I updated my answer.

**Comment by SergioRAgostinho** [comment]
So basically this..
```diff
diff --git a/cmake/pcl_find_cuda.cmake b/cmake/pcl_find_cuda.cmake
index ee70fdb43..f6daee7d1 100644
--- a/cmake/pcl_find_cuda.cmake
+++ b/cmake/pcl_find_cuda.cmake
@@ -45,9 +45,17 @@ if(CUDA_FOUND)
   if(NOT ${CUDA_VERSION_STRING} VERSION_LESS "10.0")
     set(__cuda_arch_bin "3.0 3.5 5.0 5.2 5.3 6.0 6.1 7.0 7.2 7.5")
   elseif(NOT ${CUDA_VERSION_STRING} VERSION_LESS "9.1")
-    set(__cuda_arch_bin "3.0 3.5 5.0 5.2 5.3 6.0 6.1 7.0 7.2")
+    if(NOT APPLE)
+      set(__cuda_arch_bin "3.0 3.5 5.0 5.2 5.3 6.0 6.1 7.0 7.2")
+    else()
+      set(__cuda_arch_bin "3.0 3.5 5.0 5.2 5.3 6.0 6.1")
+    endif()
   elseif(NOT ${CUDA_VERSION_STRING} VERSION_LESS "9.0")
-    set(__cuda_arch_bin "3.0 3.5 5.0 5.2 5.3 6.0 6.1 7.0")  
+    if(NOT APPLE)
+      set(__cuda_arch_bin "3.0 3.5 5.0 5.2 5.3 6.0 6.1 7.0")
+    else()
+      set(__cuda_arch_bin "3.0 3.5 5.0 5.2 5.3 6.0 6.1")
+    endif()
   elseif(NOT ${CUDA_VERSION_STRING} VERSION_LESS "8.0")
     set(__cuda_arch_bin "2.0 2.1(2.0) 3.0 3.5 5.0 5.2 5.3 6.0 6.1")
   elseif(NOT ${CUDA_VERSION_STRING} VERSION_LESS "6.5")
```

**Comment by claudiofantacci** [comment]
Yes, but I’m not sure that we are clearly understand the issue. I fear there is something I don’t understand here. Also, I have a CMake procedure to automatically set the cuda architecture based on the host GPU. Do you think it might be interesting for PCL?

**Comment by taketwo** [comment]
> Do you think it might be interesting for PCL?

I'd suggest we look at the [advanced stuff](https://github.com/opencv/opencv/blob/master/cmake/OpenCVDetectCUDA.cmake) that OpenCV has.

**Comment by SergioRAgostinho** [comment]
Thanks for the input, both. This is going to be more involved than I thought. Probably not a good idea to target it for 1.9.1.

**Comment by claudiofantacci** [comment]
> > Do you think it might be interesting for PCL?
> 
> I'd suggest we look at the [advanced stuff](https://github.com/opencv/opencv/blob/master/cmake/OpenCVDetectCUDA.cmake) that OpenCV has.

Yes, we can have a look into it. First thing to notice by just CTRL+F-ing is that architecture `7.2` is not present. That is very suspicious and it is worth investigating. I can have a look at what OpenCV does and let you know.

**Comment by SergioRAgostinho** [comment]
[compat_reports.zip](https://github.com/PointCloudLibrary/pcl/files/2606070/compat_reports.zip)

The compat reports. Nothing changed as expected.

**Comment by UnaNancyOwen** [comment]
I was tested this current release candidate https://github.com/PointCloudLibrary/pcl/pull/2631 on Windows.
It is occurred an error in CMake.
Perhaps, I think the policy change is affecting this. Do you have any ideas?


```
CMake Error at cmake/pcl_utils.cmake:63 (if):
  if given arguments:

    "EQUAL" "99"

  Unknown arguments specified
```

**Comment by SergioRAgostinho** [comment]
Yep. I just pushed the fix to the release branch.

**Comment by claudiofantacci** [comment]
@SergioRAgostinho here is the [Volta support guidelines](https://docs.nvidia.com/cuda/volta-compatibility-guide/index.html#building-volta-compatible-apps-using-cuda-9-0). Basically there is no support to `compute_72` at all. Instead of adding an exception for `APPLE` I would remove `compute_72` altogether.

**Comment by claudiofantacci** [comment]
Yes it's under `CUDA 9.*` only.
I would remove it and also I would really encourage to give the possibility to users, say with a `-DCUDA_AUTO_ARCH:BOOL=ON` to automatically detect its local GPU architecture. This would save a lot of compilation time under systems that allows to compile code from source with pre-defined configurations like `vcpkg` or `brew`. What do you think about it?

**Comment by taketwo** [comment]
@SergioRAgostinho :+1:
@claudiofantacci auto-selection is nice to have. So far I have only briefly skimmed through the OpenCV approach, but I think I saw something in this way. But I would not plan to include this in 1.9.1, of course.

**Comment by taketwo** [comment]
Does this CUDA issue hold us from releasing 1.9.1? Could we have a simple fix for the release, and then a more thorough solution (in the spirit of OpenCV) later?

**Comment by SergioRAgostinho** [comment]
Not at all. I totally agree with your suggestion. I'll finish the release tomorrow.

**Comment by SergioRAgostinho** [comment]
1.9.1 is out. @PointCloudLibrary/maintainers feel free to publish the binaries at your convenience.

**Comment by UnaNancyOwen** [comment]
I uploaded binaries for Windows! Congrats! 🎉

**Comment by SergioRAgostinho** [comment]
We got updated on homebrew straight to 1.9.1 https://github.com/Homebrew/homebrew-core/pull/34222

**Comment by rfsch** [comment]
I think vcpkg upgrade to pcl 1.9.1 is not working. 

I have 1.8 installed and vcpkg upgrade tells me all libraries are current. 
Do I need to uninstall 1.8. in order to get 1.9.1 _
thanks.

**Comment by SergioRAgostinho** [comment]
If it's really a problem with the vcpkg, the best is to give them a ping at https://github.com/Microsoft/vcpkg . We can't really advise you on this.

**Comment by claudiofantacci** [comment]
@rfsch the port on `vcpkg` is pointing to version [`1.9.1`](https://github.com/Microsoft/vcpkg/blob/master/ports/pcl/portfile.cmake). What I think you may be confusing is the way to update `vcpkg` ports that you do with a `git pull` from within the `vcpkg` installation foler, and not through `vcpkg update`. `vcpkg update` checks whether any of your _current installed_ libraries are outdated with respect to the _local version_ of the portfile (i.e. gotten through your latest `git pull`).

**Comment by rfsch** [comment]
@claudiofantacci my fault I thought vcpkg update would do this. 
So I just need to pull the new version from https://github.com/PointCloudLibrary/pcl.git ? 

grazie!

**Comment by rfsch** [comment]
@claudiofantacci thanks!
